server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8101/eureka

spring:
  application:
    name: apigateway-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      routes:

#   user-service /auth POST
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/auth
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

#   user-service /users POST
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

#   user-service POST, GET, PUT, DELETE method (AuthorizationHeaderFilter)
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
            - Method=POST,GET,PUT,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

#   user-service actuator
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/actuator/**
            - Method=POST,GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

#   item-service POST,GET,PUT
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/item-service/**
            - Method=POST,GET,PUT
          filters:
            - RewritePath=/item-service/(?<segment>.*), /$\{segment}

#   cart-service POST, GET, PUT, DELETE
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart-service/**
            - Method=POST,GET,PUT,DELETE
          filters:
            - RewritePath=/cart-service/(?<segment>.*), /$\{segment}

#   order-service POST, GET, PUT, DELETE
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
            - Method=POST,GET,PUT,DELETE
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}

      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true

#filters example
#          filters:
#            - AddRequestHeader=user-request, user-request-header2
#            - AddResponseHeader=user-response, user-response-header2
#            - name: CustomFilter
#            - name: LoggingFilter
#              args:
#                baseMessage: Custom Logging Filter
#                preLogger: true
#                postLogger: true

#jwt:
#  header: Authorization
#  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh
