server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/MJLEE/Desktop/mjlee/git_workspace/nude-msa/git-local-repo
